### ISSUE TITLE
Finalize

### ISSUE THREAD

**Issue by fprochazka** [fprochazka/fi-muni-bachelors-thesis#2]
Sorted by importance:

* [x] Roadmap
    * [x] Write: Doctrine
* [x] Refactoring
    * [x] Write: Designing new Kdyby Coding Standard
    * [x] Write: Summary
* [x] Write: Conclusion and future work
* [x] Theory - the chapter is shit, rewrite a bit and get a better citations
* [x] Citations (get rid of links to wikipedia)
* [x] Write: Keywords
* [x] Write: Acknowledgement
* [x] Write: Abstract CZ
* [x] Write: Abstract EN
* [x] Grammar 

---

* [Up-to-date PDF snapshot of thesis](https://github.com/fprochazka/fi-muni-bachelors-thesis/blob/master/dist/thesis.pdf)

**Comment by fprochazka** [comment]
If you want to help me, It would be awesome if you could write comments here and I'll be fixing the mistakes tomorrow after I finish writing the remaining sections. Thanks!

**Comment by Grez** [comment]
- [x] filip procházka v úvodu se ti špatně dělí
- [x] PHPStan vs PhpStan
- [x] opravdu se píše "unite tested" nebo je to "e" překlep?
- [x] "important part of this thesis.." dvě tečky
- [x] now-days by asi mělo být "nowadays"
- [x] Github vs GitHub
- [ ] 3.2.7 odkazuješ se na "3.2", ale to je o něčem jiném
- [x] Fig. 3.3 chybí ti tam středník :D
- [x] defacto se píše s mezerou
- [x] "because its of" máš to trochu proházené :-)

**Comment by pavelkouril** [comment]
- [x] you really don't want to use words like "wanna" (p. 1); (the same applies for "don't", "it's", etc., so look for those as well, and replace them with proper versions)
- [x] footnotes are usually a sentence, so start it with a capital letter and end it with a dot; speaking of which, the format of the footnotes you have feels weird, once you realize they should be sentences :)
- [ ] the footnote on p.1 probably should be a proper citation instead?
- [x] "function begins with set"; maybe try to inline a monospace for for the set, so it looks like `set` on github? :) (or italic, try that as well)
- [x] might be a good idea to write classes and namespaces like Nette\Tester, Kdyby\Doctrine, Kdyby\DoctrineCollectionsReadonly ..., etc. in italic; try it, there's a good chance it will look nicer :) (or the inlined monospace, like UI\Presenter on p. 16); be consistent ;)
- [x] p. 8, why officially released in quotation marks?
- [x] p. 21, geocoder breaks the layout
- [x] 3/4 figure descriptions end with a dot, so end the first one with dot as well (or remove the dots on the rest), for consistency :)

Just had just a quick look, since the snapshot is 3 days old and I was not sure how relevant the comments would be now. :)

**Comment by fprochazka** [comment]
* [x] Hned v první části "Introduction", třetí slovo ve druhým odstavci - chybí ti tam "e", protože takhle to není kariéra, ale spíš nějakej pečovatel nebo tak 😀.
* [x] "Doslova" není "literary", ale "literally"
* [x] a hned za tím "flowed" by mělo být spíš "flown"
* [x] an HTML misto a HTML
